theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "eno1"
interval = 2

[[block]]
block = "disk_space"
path = "/"
format = "SSD {available}"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 5.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_avail;G}"
format_swap = "{swap_free;G}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
format = "{average}C"
collapsed = false

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m/%Y %R"
